GET http://localhost:5102/secret
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IndrIiwic3ViIjoid2siLCJqdGkiOiI0Yjk3MzQyNiIsImF1ZCI6WyJodHRwczovL2xvY2FsaG9zdDo3MjgxIiwiaHR0cDovL2xvY2FsaG9zdDo1MTAyIl0sIm5iZiI6MTY1NTkxNTY4NCwiZXhwIjoxNjYzODY0NDg0LCJpYXQiOjE2NTU5MTU2ODQsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.ecYt5pIDCFKRPFWRLOzUJt6XnlXLkzMrVkGJP_VgZO4

###
curl -i http://localhost:5102/secret